<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nea Amanda Br Saragih">
<meta name="dcterms.date" content="2024-01-12">

<title>Pengaruh Ekspor Kakao Terhadap Produk Domestik Bruto (PDB) di Indonesia 2010-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Kakao Terhadap Produk Domestik Bruto (PDB) di Indonesia 2010-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nea Amanda Br Saragih </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 12, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid" width="355"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Pertumbuhan ekonomi adalah salah satu indikator penting untuk mengukur kemajuan suatu negara. Pertumbuhan ekonomi menjadi tujuan strategis bagi setiap negara karena dapat mencerminkan kemajuan dan kesejahteraan masyarakatnya. Indonesia merupakan salah satu produsen kakao terbesar di dunia dengan potensi ekonomi yang besar. Ekspor kakao merupakan salah satu sektor yang memiliki kontribusi positif terhadap pertumbuhan ekonomi Indonesia.</p>
<p>Meningkatnya permintaan internasional terhadap kakao, baik sebagai bahan baku industri makanan maupun minuman, telah membuka peluang besar bagi Indonesia untuk meningkatkan ekspor kakao. Dalam konteks ini, penelitian tentang Pengaruh Ekspor Kakao terhadap PDB di Indonesia menjadi relevan karena dapat memberikan pemahaman lebih mendalam tentang kontribusi ekspor kakao dalam mendorong pertumbuhan ekonomi nasional.</p>
<p>Penelitian ini bertujuan untuk menganalisis pengaruh ekspor kakao terhadap Produk Domestik Bruto (PDB) Indonesia selama periode 2010-2022. Dengan mendapatkan pemahaman yang lebih mendalam tentang hubungan antara ekspor kakao dan pertumbuhan ekonomi, kebijakan yang tepat dapat diambil untuk meningkatkan pertumbuhan ekonomi Indonesia secara keseluruhan.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Pada penelitian ini penulis mengambil objek penelitian dari UN Comtrade Database dan World Development Indicators. Ruang lingkup penelitian ini terdapat 2 variabel yaitu nilai ekspor kakao dari Indonesia serta Nilai Produk Domestik Bruto (PDB) Indonesia. Data yang digunakan adalah data yang bersifat time series yaitu dalam kurun waktu 2010-2022. Satuan pada data ini telah diubah ke dalam USD untuk memudahkan penyetaraan mata uang secara internasional, dan dengan batasan ruang lingkup ini dapat membantu mengidentifikasi masalah yang akan dibahas.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan uraian latar belakang diatas maka yang menjadi masalah pokok pada penelitian ini adalah:</p>
<ol type="1">
<li>Apakah terdapat pengaruh dari ekspor kakao terhadap PDB Indonesia selama periode 2010-2022?</li>
<li>Apakah terdapat hubungan antara jumlah ekspor kakao dengan pertumbuhan ekonomi Indonesia?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Berdasarkan latar belakang dan permasalahan diatas maka tujuan dari penelitian ini adalah untuk mengetahui pengaruh ekspor kakao terhadap PDB di Indonesia dan mengetahui hubungan antara jumlah ekspor kakao dengan pertumbuhan ekonomi di Indonesia.</p>
<p>Adapun manfaat dari penelitian ini antara lain:</p>
<ol type="a">
<li>Bagi Penulis</li>
</ol>
<p>Diharapkan penelitian ini bisa memberikan pemahaman yang lebih mendalam tentang kontribusi sektor ekspor kakao terhadap pertumbuhan ekonomi Indonesia, memberikan wawasan dan pengetahuan baru bagi peneliti, akademisi, dan masyarakat umum mengenai hubungan antara ekspor kakao dan pertumbuhan ekonomi di Indonesia.</p>
<ol start="2" type="a">
<li>Bagi instansi</li>
</ol>
<p>Sebagai bahan masukan dan informasi kepada pemerintah dan pelaku industri kakao mengenai pentingnya pengembangan sektor ekspor kakao untuk mendorong pertumbuhan ekonomi negara.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Package yang digunakan penulis yaitu:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'WDI'</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'kableExtra'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Ekspor adalah perdagangan lintas batas atau pertukaran barang produksi dalam negeri dengan barang luar negeri (Amir, 2000). Peningkatan ekspor akan memberikan kontribusi yang positif terhadap pertumbuhan ekonomi suatu negara. Salvator (1990) menegaskan bahwa ekspor merupakan salah satu mesin pendorong pertumbuhan ekonomi. Kajian yang dilakukan oleh Salvator menunjukkan bahwa ekspor merupakan salah satu faktor utama bagi negara berkembang untuk dapat meningkatkan pertumbuhan ekonomi.</p>
<p>Kakao merupakan salah satu komoditi hasil perkebunan yang mempunyai peran yang penting pada perekonomian Indonesia. Kakao adalah salah satu komoditas ekspor dari subsektor perkebunan yang menjadi komoditas unggulan nasional yang memberikan sumbangan devisa ketiga terbesar yaitu sebesar US$ 1,2 miliar setelah kelapa sawit dan karet (Goenadi et al., 2007). Hal &nbsp;ini menunjukkan &nbsp;bahwa kakao &nbsp;berperan &nbsp;penting &nbsp;dalam &nbsp;meningkatkan perekonomian.</p>
<p>Beberapa studi sebelumnya telah dilakukan untuk mengeksplorasi hubungan antara ekspor kakao dan pertumbuhan ekonomi di berbagai negara. Beberapa penelitian tersebut menunjukkan bahwa ekspor kakao dapat memberikan kontribusi positif terhadap pertumbuhan ekonomi melalui peningkatan produksi, peningkatan pendapatan petani kakao, penciptaan lapangan kerja, pembangunan infrastruktur, dan peningkatan pendapatan negara melalui penerimaan ekspor.</p>
<p>Dalam tulisan ini, penelitian tentang “Pengaruh Ekspor Kakao Terhadap Produk Domestik Bruto (PDB) di Indonesia” memiliki relevansi penting dalam konteks pengembangan sektor kakao dan kaitannya dengan pertumbuhan ekonomi negara. Melalui penelitian ini, diharapkan dapat memberikan wawasan baru dan informasi penting dalam upaya pengembangan sektor kakao dan pertumbuhan ekonomi&nbsp;di&nbsp;Indonesia.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>tahun</th>
<th>ekspor kakao (x)</th>
<th>GDP (y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2010</td>
<td>46097711</td>
<td>7.550942e+11</td>
</tr>
<tr class="even">
<td>2011</td>
<td>51287028</td>
<td>8.929691e+11</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>55128651</td>
<td>9.178699e+11</td>
</tr>
<tr class="even">
<td>2013</td>
<td>47963350</td>
<td>9.125241e+11</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>45052915</td>
<td>8.908148e+11</td>
</tr>
<tr class="even">
<td>2015</td>
<td>36559328</td>
<td>8.608542e+11</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>46659384</td>
<td>9.318774e+11</td>
</tr>
<tr class="even">
<td>2017</td>
<td>41397404</td>
<td>1.015619e+12</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>44512303</td>
<td>1.042272e+12</td>
</tr>
<tr class="even">
<td>2019</td>
<td>47677412</td>
<td>1.119100e+12</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>44062401</td>
<td>1.059055e+12</td>
</tr>
<tr class="even">
<td>2021</td>
<td>70187996</td>
<td>1.186505e+12</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>76895405</td>
<td>1.319100e+12</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data time series 2010-2022, data yang dipakai ialah data yang telah diolah dengan sumber UN Comtrade database dan World Development Indicators.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Users/USER/Documents/metopel/latihan'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'datametopel1.xlsx'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>dat,y<span class="sc">~</span>x)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>x,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"ekspor kakao"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot ekspor kakao yang dipengaruhi error</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Users/USER/Documents/metopel/latihan'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'datametopel1.xlsx'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>dat,y<span class="sc">~</span>x)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>y,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"GDP"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini merbaksud mencari hubungan antara GDP dan ekspor kakao. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah GDP dan <span class="math inline">\(x_t\)</span> adalah Ekspor kakao.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variabel</th>
<th>Estimate Std</th>
<th>Error</th>
<th>t value</th>
<th>Prob (.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>5.158e+11</td>
<td>1.474e+11</td>
<td>3.50</td>
<td>0.00497</td>
</tr>
<tr class="even">
<td>x</td>
<td>9.486e+03</td>
<td>2.865e+03</td>
<td>3.31</td>
<td>0.00695</td>
</tr>
<tr class="odd">
<td>R Squared</td>
<td>0.4991</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjuated R Squared</td>
<td>0.4535</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>F-statistic</td>
<td>10.96</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Prob(F-statistic)</td>
<td>0.006948</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Hasil regresi setelah dimasukkan ke dalam rumus persamaan adalah:</p>
<p>Y = 5.158 + 9.485X</p>
<p>Ekspor mempunyai peran yang penting dalam meningkatkan Pertumbuhan Domestik Bruto (PDB), hal ini ditunjukkan dari nilai variabel X yang positif. Jika dilihat dari hasil regresinya, diketahui bahwa pertumbuhan ekonomi tidak sepenuhnya dipengaruhi oleh ekspor saja namun terdapat faktor-faktor lain.</p>
<p>Nilai intercept adalah 5.158, ini berarti bahwa ketika variabel independen sama dengan nol, diperkirakan nilai variabel dependen sebesar 5.158. Coefficient adalah besarnya perubahan y (PDB) yang diharapkan ketika x (ekspor kakao) mengalami perubahan satu satuan, dalam hal ini adalah 9.485, ini berarti bahwa setiap kenaikan satu satuan pada ekspor kakao, diperkirakan akan meningkatkan Pertumbuhan Domestik Bruto (PDB) sebesar 9.485.</p>
<p>Adjusted R-squared menunjukkan seberapa baik model ini menjelaskan variasi dalam data, dalam hal ini adalah &nbsp;0.4535. Ini berarti sekitar 45,35% variasi dalam Pertumbuhan Domestik Bruto (PDB) dapat dijelaskan oleh ekspor kakao dan sisanya di jelaskan oleh faktor lain. Nilai F-statistik sebesar 10.96 menunjukkan bahwa variabel Pertumbuhan Domestik Bruto (PDB) berpengaruh terhadap tingkat pertumbuhan ekonomi.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Users/USER/Documents/metopel/latihan'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'datametopel1.xlsx'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>dat,y<span class="sc">~</span>x)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = dat)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.979e+11 -5.821e+10 -1.701e+09  1.043e+11  1.511e+11 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 5.158e+11  1.474e+11    3.50  0.00497 **
x           9.486e+03  2.865e+03    3.31  0.00695 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.124e+11 on 11 degrees of freedom
Multiple R-squared:  0.4991,    Adjusted R-squared:  0.4535 
F-statistic: 10.96 on 1 and 11 DF,  p-value: 0.006948</code></pre>
</div>
</div>
<p>Setiap kenaikan nilai ekspor kakao dengan diasumsikan nilainya 1, maka dapat meningkatkan Pertumbuhan Domestik Bruto (PDB) sebesar 9.485.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Setelah dilakukan penelitian melalui sistem regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independent, maka di dapatkan kesimpulan sebagai berikut:</p>
<ol type="1">
<li><p>Ekspor kakao memiliki pengaruh terhadap pertumbuhan ekonomi di Indonesia pada periode 2010-2022, Ekspor mempunyai peran yang penting dalam meningkatkan Pertumbuhan Domestik Bruto (PDB), namun tidak sepenuhnya dipengaruhi oleh ekspor saja namun terdapat faktor-faktor lain.</p></li>
<li><p>Hubungan antara jumlah ekspor kakao dengan PDB Indonesia dapat dilihat dari nilai ekspor kakao yang memiliki nilai positif, melalui penerimaan ekspor kakao yang diperoleh dapat memberikan kontribusi positif terhadap pertumbuhan ekonomi melalui peningkatan produksi, peningkatan pendapatan petani kakao, penciptaan lapangan kerja, pembangunan infrastruktur, dan peningkatan pendapatan negara.</p></li>
</ol>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Adi. (n.d.). <em>Data Ekspor Kakao Indonesia: Potensi dan Tantangan di Masa Depan</em>. Retrieved from jangkargroups.co.id: https://jangkargroups.co.id/</p>
<p>Augustin, N. P. (2022). <em>Edy Prasetyo 2 , Siswanto Imam Santoso 3 1*</em>. <em>6</em>, 442–455. https://www.researchgate.net/publication/362140863_Analisis_Daya_Saing_dan_Trend_Ekspor_Kakao_Indonesia_ke_Lima_Negara_Tujuan_Tahun_2010-2019</p>
<p>Ginting, A. M. (2017). Analisis Pengaruh Ekspor Terhadap Pertumbuhan Ekonomi Indonesia. <em>Buletin Ilmiah Litbang Perdagangan</em>, <em>11</em>(1), 1–20. https://doi.org/10.30908/bilp.v11i1.185</p>
<p>hestanto. (n.d.). <em>Pengertian Ekspor Menurut Para Ahli</em>. Retrieved from hestanto.web.id: https://www.hestanto.web.id/mengenal-ekspor-menurut-para-ahli/</p>
<p>Tumanggor, j. (2023). Analisis Ekspor Kakao Indonesia Periode 1991-2020 (Doctoral dissertation, Universitas Jambi). https://repository.unja.ac.id/55234/5/Bab%20I-15-22.pdf</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>